config/routes.rb
Newspaper::Application.routes.draw do
  post "article/create"
  get "article/read/:id", :to => "article#read"
  patch "article/update/:id", :to => "article#update", as: :article_update
  get "article/destroy/:id", :to => "article#destroy"
  get "article/index"
  get "article/new"
  get "article/edit/:id", :to => "article#edit"
  get "/", :to => "article#index"
  get "/about", :to => "static#about"
  get "/search", :to => "static#search"
  get "/random", :to => "article#random"
  post "/search", :to => "article#search_post"
  get "/author_search", :to => "static#author_search"
  post "/author_search", :to => "article#author_return"
  post "/add_comment", :to => "article#add_comment"
  

end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  before_save { self.body = body.downcase }

  validates :body, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/article_controller.rb
class ArticleController < ApplicationController
  def create
    @article = Article.new(post_params)
    @article.save
    
    redirect_to article_index_path
  end
  
  def read
    article_id = params["id"]
    @article = Article.find(article_id)
  end

  def update
    article_id = params["id"]
    
    @article = Article.find(params[:id])
    @article.update(params[:article].permit(:author, :title, :contact, :location, :body))
    
    redirect_to article_index_path
  end

  def destroy
    article_id = params["id"]
    Article.destroy(article_id)
    
    redirect_to article_index_path
  end

  def index
    @articles = Article.all()
  end

  def new
  end

  def edit
    article_id = params["id"]
    @article = Article.find(article_id)
  end
  
  def random
    count = Article.count()
  
    @article = nil
    until not @article.nil?
      begin
        random_number= rand(0..count)
        @article = Article.find(random_number)
      rescue =>e
        puts e.message
      end
    end 
      
  end
  
  def search_post
    @search_term = params["search_term"]
    
    @article = Article.find_by title: @search_term
  end
  
  def author_return
    @author_search_term = params["author_search_term"]
    #@articles = Article.find_by author: @author_search_term
    @articles = Article.where("author = ?", params["author_search_term"])
  end
  
  def add_comment
    count = Comment.count()
    new_comment = params["new_comment"]
    
    article_id = params["article_id"]

    
    @article = Article.find(article_id)
    @comment = @article.comments.build(body: new_comment, date: DateTime.now.to_date )
    @comment.save
    redirect_to "/article/read/#{article_id}"
  end
  
  private
    def post_params
      params.require(:article).permit(:title, :author, :location, :contact, :body)
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/article_helper.rb
module ArticleHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/article/author_return.html.erb
<div class="col-xs-12 col-sm-6 col-sm-offset-3 col-md-6 col-md-offset-3">
  <h1>Results for "<%= @author_search_term %>"</h1>
  <% if not @articles.nil? %>
  
   <% @articles.each do |article| %>

      <h3><%= article.title %></h3>
      <p>
        By: <%= article.author %>  |
        Location: <%= article.location %>  |
        Contact author: <a href="#"><%= article.contact %></a><br>
        Published at: <%= article.created_at %><br />
        <br><%= simple_format(article.body) %><br>
        <a href="/article/read/<%= article.id %>">View</a>
      </p>
      <br />

   <% end %>
 
  <% else %>
    <h3>Nothing found</h3>
  <% end %>
  
</div>

app/views/article/create.html.erb
<h1>Article#create</h1>
<p>Find me in app/views/article/create.html.erb</p>

app/views/article/destroy.html.erb
<h1>Article#destroy</h1>
<p>Find me in app/views/article/destroy.html.erb</p>

app/views/article/edit.html.erb
<div class="col-xs-12 col-sm-6 col-sm-offset-4 col-md-6 col-md-offset-4">
<h1>Edit Article</h1><br />
</div>

<%= form_for(@article, :url => article_update_path(@article)) do |f| %>
<div class="col-xs-12 col-sm-6 col-sm-offset-4 col-md-6 col-md-offset-4">
  <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </p>
   
   <p>
    <%= f.label :author %>
    <%= f.text_field :author %>
   </p>
  
   <p>
    <%= f.label :contact %>
    <%= f.text_field :contact %>
   </p>
 
   <p>
    <%= f.label :location %>
    <%= f.text_field :location %>
   </p>
  
   <p>
    <%= f.label :body %>
    <%= f.text_area :body %>
   </p>
 
   <p>
    <%= f.submit 'Edit Article' %>
   </p>
  
 </div>

  
<% end %>

app/views/article/index.html.erb
<h1>News</h1><br />

<% @articles.each do |article| %>
<div class="col-xs-12 col-sm-6 col-md-4">
  <h3><%= article.title %></h3>
  <p>
    By: <%= article.author %>  |
    Location: <%= article.location %>  |
    Contact author: <a href="#"><%= article.contact %></a><br>
    Published at: <%= article.created_at %><br />
    <br><%= simple_format(article.body) %><br>
    <a href="/article/read/<%= article.id %>">View</a>
  </p>
  <br />
</div>
<% end %>

app/views/article/new.html.erb
<h1>Add an article</h1><br />

<%= form_for :article, url: article_create_path do |f| %>
  <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </p>
   
   <p>
    <%= f.label :author %>
    <%= f.text_field :author %>
  </p>
  
   <p>
    <%= f.label :location %>
    <%= f.text_field :location %>
  </p>
 
   <p>
    <%= f.label :contact %>
    <%= f.text_field :contact %>
  </p>
  
  <p>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </p>
  
  <p>
    <%= f.submit 'Publish' %>
  </p>
  

  
<% end %>

app/views/article/random.html.erb
<div class="col-xs-12 col-sm-6 col-sm-offset-3 col-md-6 col-md-offset-3">
  <h1>Random</h1>
  <h3><%= @article.title %></h3>
  <p>
    By: <%= @article.author %>  |
    Location: <%= @article.location %>  |
    Contact author: <a href="#"><%= @article.contact %></a><br>
    Published at: <%= @article.created_at %><br />
    <br><%= simple_format(@article.body) %><br>
    <a href="/article/edit/<%= @article.id %>">Edit </a>|
<a href="/article/destroy/<%= @article.id %>">Delete</a>
  </p>
  <br />
</div>

app/views/article/read.html.erb
<div class="col-xs-12 col-sm-6 col-sm-offset-3 col-md-6 col-md-offset-3">
  <h3><%= @article.title %></h3>
  <p>
    By: <%= @article.author %>  |
    Location: <%= @article.location %>  |
    Contact author: <a href="#"><%= @article.contact %></a><br>
    Published at: <%= @article.created_at %><br />
    <br><%= simple_format(@article.body) %><br>
    <a href="/article/edit/<%= @article.id %>">Edit </a>|
<a href="/article/destroy/<%= @article.id %>">Delete</a>
  </p>
  <br />
  
  <h3>Comments</h3>
    <% @article.comments.each do |comment| %>

    <p><%= comment.date %><br>
       <%= comment.body %>
    </p>
    
    
    <br>
  
  <% end %>


  
  <form method="POST" action="/add_comment">
    <%= token_tag form_authenticity_token %>
      Comment: <input type="text" name="new_comment">
      <input type="hidden" name="article_id" value="<%= @article.id %>">
    <button class="submit">Submit</button>
  </form>
</div>

app/views/article/search_post.html.erb
<div class="col-xs-12 col-sm-6 col-sm-offset-3 col-md-6 col-md-offset-3">
  <h1>Results for "<%= @search_term %>"</h1>
  <% if not @article.nil? %>
    <h3><%= @article.title %></h3>
    <p>
      By: <%= @article.author %>  |
      Location: <%= @article.location %>  |
      Contact author: <a href="#"><%= @article.contact %></a><br>
      Published at: <%= @article.created_at %><br />
      <br><%= simple_format(@article.body) %><br>
      <a href="/article/edit/<%= @article.id %>">Edit </a>|
  <a href="/article/destroy/<%= @article.id %>">Delete</a>
    </p>
    <br />
  <% else %>
    <h3>Nothing found</h3>
  <% end %>
  
</div>

app/views/article/update.html.erb
<h1>Article#update</h1>
<p>Find me in app/views/article/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/3.0.2/css/bootstrap.min.css"
  
  <%= csrf_meta_tags %>
</head>
 
<body>
 
<!-- PART 3 - ROWS AND COLUMNS -->
    <!-- Fixed navbar -->
    <div class="navbar navbar-inverse navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Newspaper App</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="/">Home</a></li>
            <li><a href="/about">About</a></li>
            <li><a href="/article/new">New</a></li>
            <li><a href="/article/index">Index</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
 
 
<!-- PART 1 - THE JUMBOTRON -->
    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron" style="background-image:url(http://us.123rf.com/400wm/400/400/damianpalus/damianpalus0805/damianpalus080500040/3019814-newspaper-stack-on-white-background.jpg);">
      <div class="container" >
     
        <h1>Newspaper Mockup</h1>
      </div>
    </div>
 
    
<%= yield %>
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
 
    <!-- Latest compiled and minified JavaScript -->
    <script src="http://netdna.bootstrapcdn.com/bootstrap/3.0.2/js/bootstrap.min.js"></script>
</body>
 
</html>